### ISSUE TITLE
Error with import in module cli

### ISSUE THREAD

**Issue by gunshi** [leehomyc/Img2Img-Translation-Networks#3]
On running
python -m dataset.create_image_pair_list --first_dataset=./../data/img2img/horse.csv --second_dataset=./../data/img2img/zebra.csv --output_file=./../data/img2img/horse_zebra.csv

I get the error:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tushar/codes/gunsshi/Img2Img-Translation-Networks/dataset/create_image_pair_list.py", line 7, in <module>
    from cli import configure_script
ImportError: cannot import name 'configure_script'

The cli module which i got through "pip install pyCLI", seems to not have configure_script() defined anywhere in its source code.
Kindly help, thanks.

**Comment by gunshi** [comment]
Commented out the module import and its function call( configure_script() ), and the csv file did get generated, so I hope everything worked alright.

**Comment by wxh001qq** [comment]
have you figure out it? i also find that

**Comment by gunshi** [comment]
Yes, just comment out the import and the configure_script() call.
