### ISSUE TITLE
Conversion to paired image to image translation

### ISSUE THREAD

**Issue by gunshi** [leehomyc/Img2Img-Translation-Networks#4]
Hey, 
I want to try paired image to image translation within the framework of cyclic consistency and shared latent space etc mentioned in the paper.
To do that, the only thing i have to change in this code is remove the shuffling when creating file paths of images from the dataset directory for csv file creation, right?

**Comment by leehomyc** [comment]
yep

**Comment by gunshi** [comment]
Okay thanks.
And if I wanted to translate, say 360x640 images(want to maintain aspect ratio) instead of 256x256, how would I do that? Since the layers are fully convolutional, and i wanted to use the resnet model, I thought I'll just change the output shape expected by 'general_deconv2d' to what i want, and change size parameters in various files. Not sure if there's anything else?

edit: I think i'll have to also add another few layers of convolutions to discriminator specs? Can you guide with how to do that exactly?

**Comment by gunshi** [comment]
Also, were the lines:
```
        self.input_a = tf.placeholder(
            tf.float32, [
                1,
                model.IMG_WIDTH,
                model.IMG_HEIGHT,
                model.IMG_CHANNELS,
], name="input_A")
```

in main.py intended to be
```

        self.input_a = tf.placeholder(
            tf.float32, [
                1,
                model.IMG_HEIGHT,
                model.IMG_WIDTH,
                model.IMG_CHANNELS,
], name="input_A")
```

instead?

Because I get an error here saying :
ValueError: Cannot feed value of shape (1, 360, 640, 3) for Tensor 'input_A:0', which has shape '(1, 640, 360, 3)'

**Comment by gunshi** [comment]
Flipping those parameters fixes things.
